-- Catálogo inicial de espécies (192) com nomes populares em português.
-- Nomes científicos conferidos na API do GBIF (species/match); gbif_key é a
-- chave do táxon aceito no GBIF, ou NULL quando o GBIF agrupa táxons de uso
-- distinto (ex.: limão-cravo, laranja) e mantivemos o nome de uso corrente.
WITH inserted AS (
    INSERT INTO species (scientific_name, family, category, gbif_key)
    VALUES
    ('Monstera deliciosa', 'Araceae', 'folhagem', 2868241),
    ('Epipremnum aureum', 'Araceae', 'folhagem', 2868323),
    ('Philodendron hederaceum', 'Araceae', 'folhagem', 2871003),
    ('Thaumatophyllum bipinnatifidum', 'Araceae', 'folhagem', 9689104),
    ('Zamioculcas zamiifolia', 'Araceae', 'folhagem', 2869014),
    ('Spathiphyllum wallisii', 'Araceae', 'folhagem', 2869680),
    ('Anthurium andraeanum', 'Araceae', 'folhagem', 2872695),
    ('Dieffenbachia seguine', 'Araceae', 'folhagem', 2869345),
    ('Aglaonema commutatum', 'Araceae', 'folhagem', 2866467),
    ('Syngonium podophyllum', 'Araceae', 'folhagem', 2867866),
    ('Caladium bicolor', 'Araceae', 'folhagem', 2868390),
    ('Dracaena trifasciata', 'Asparagaceae', 'folhagem', 11041822),
    ('Dracaena fragrans', 'Asparagaceae', 'folhagem', 5304583),
    ('Dracaena marginata', 'Asparagaceae', 'folhagem', 10818704),
    ('Dracaena sanderiana', 'Asparagaceae', 'folhagem', 7431653),
    ('Beaucarnea recurvata', 'Asparagaceae', 'folhagem', 2768035),
    ('Chlorophytum comosum', 'Asparagaceae', 'folhagem', 2774846),
    ('Aspidistra elatior', 'Asparagaceae', 'folhagem', 2769937),
    ('Asparagus setaceus', 'Asparagaceae', 'folhagem', 2768686),
    ('Ficus lyrata', 'Moraceae', 'folhagem', 5361899),
    ('Ficus elastica', 'Moraceae', 'folhagem', 7835333),
    ('Ficus benjamina', 'Moraceae', 'folhagem', 5361932),
    ('Maranta leuconeura', 'Marantaceae', 'folhagem', 2761337),
    ('Goeppertia makoyana', 'Marantaceae', 'folhagem', 7708211),
    ('Nephrolepis exaltata', 'Nephrolepidaceae', 'folhagem', 2650927),
    ('Adiantum raddianum', 'Pteridaceae', 'folhagem', 2651826),
    ('Platycerium bifurcatum', 'Polypodiaceae', 'folhagem', 7126767),
    ('Rhapis excelsa', 'Arecaceae', 'folhagem', 2736747),
    ('Dypsis lutescens', 'Arecaceae', 'folhagem', 2735935),
    ('Chamaedorea elegans', 'Arecaceae', 'folhagem', 2734661),
    ('Peperomia obtusifolia', 'Piperaceae', 'folhagem', 3086423),
    ('Pilea peperomioides', 'Urticaceae', 'folhagem', 5669632),
    ('Begonia maculata', 'Begoniaceae', 'folhagem', 7303475),
    ('Tradescantia zebrina', 'Commelinaceae', 'folhagem', 2765359),
    ('Tradescantia pallida', 'Commelinaceae', 'folhagem', 2765221),
    ('Hedera helix', 'Araliaceae', 'folhagem', 8351737),
    ('Heptapleurum arboricola', 'Araliaceae', 'folhagem', 3038724),
    ('Codiaeum variegatum', 'Euphorbiaceae', 'folhagem', 3071476),
    ('Aloe vera', 'Asphodelaceae', 'suculenta', 2777724),
    ('Haworthiopsis attenuata', 'Asphodelaceae', 'suculenta', 9388529),
    ('Crassula ovata', 'Crassulaceae', 'suculenta', 5362063),
    ('Echeveria elegans', 'Crassulaceae', 'suculenta', 8315197),
    ('Kalanchoe blossfeldiana', 'Crassulaceae', 'suculenta', 2985944),
    ('Sedum morganianum', 'Crassulaceae', 'suculenta', 5690408),
    ('Graptopetalum paraguayense', 'Crassulaceae', 'suculenta', 7334731),
    ('Curio rowleyanus', 'Asteraceae', 'suculenta', 3149649),
    ('Euphorbia milii', 'Euphorbiaceae', 'suculenta', 3067157),
    ('Schlumbergera truncata', 'Cactaceae', 'suculenta', 5383983),
    ('Opuntia microdasys', 'Cactaceae', 'suculenta', 7283961),
    ('Cereus jamacaru', 'Cactaceae', 'suculenta', 7282182),
    ('Adenium obesum', 'Apocynaceae', 'suculenta', 7155887),
    ('Agave americana', 'Asparagaceae', 'suculenta', 2767031),
    ('Cleistocactus winteri subsp. colademono', 'Cactaceae', 'suculenta', NULL),
    ('Aporocactus flagelliformis', 'Cactaceae', 'suculenta', 7283331),
    ('Rosa × hybrida', 'Rosaceae', 'flor', NULL),
    ('Phalaenopsis spp.', 'Orchidaceae', 'flor', 2804680),
    ('Dendrobium nobile', 'Orchidaceae', 'flor', 5317489),
    ('Cattleya labiata', 'Orchidaceae', 'flor', 2801162),
    ('Oncidium spp.', 'Orchidaceae', 'flor', 2834394),
    ('Streptocarpus ionanthus', 'Gesneriaceae', 'flor', 6710927),
    ('Hydrangea macrophylla', 'Hydrangeaceae', 'flor', 2985994),
    ('Rhododendron simsii', 'Ericaceae', 'flor', 7327627),
    ('Bougainvillea spectabilis', 'Nyctaginaceae', 'flor', 7167078),
    ('Hibiscus rosa-sinensis', 'Malvaceae', 'flor', 3152559),
    ('Ixora coccinea', 'Rubiaceae', 'flor', 8793122),
    ('Gardenia jasminoides', 'Rubiaceae', 'flor', 5335125),
    ('Trachelospermum jasminoides', 'Apocynaceae', 'flor', 3169713),
    ('Allamanda cathartica', 'Apocynaceae', 'flor', 3169836),
    ('Cestrum nocturnum', 'Solanaceae', 'flor', 2928791),
    ('Brunfelsia uniflora', 'Solanaceae', 'flor', 2932913),
    ('Petunia × atkinsiana', 'Solanaceae', 'flor', 2928859),
    ('Lavandula angustifolia', 'Lamiaceae', 'flor', 2927305),
    ('Pelargonium × hortorum', 'Geraniaceae', 'flor', 2891604),
    ('Impatiens walleriana', 'Balsaminaceae', 'flor', 2891772),
    ('Impatiens hawkeri', 'Balsaminaceae', 'flor', 4193702),
    ('Viola × wittrockiana', 'Violaceae', 'flor', 5331389),
    ('Helianthus annuus', 'Asteraceae', 'flor', 9206251),
    ('Leucanthemum vulgare', 'Asteraceae', 'flor', 8848598),
    ('Chrysanthemum × morifolium', 'Asteraceae', 'flor', 3150767),
    ('Gerbera jamesonii', 'Asteraceae', 'flor', 7969761),
    ('Tagetes erecta', 'Asteraceae', 'flor', 3088488),
    ('Zinnia elegans', 'Asteraceae', 'flor', 3111754),
    ('Dianthus caryophyllus', 'Caryophyllaceae', 'flor', 3085420),
    ('Lilium spp.', 'Liliaceae', 'flor', 2752977),
    ('Agapanthus africanus', 'Amaryllidaceae', 'flor', 2854740),
    ('Hippeastrum spp.', 'Amaryllidaceae', 'flor', 2854235),
    ('Dietes bicolor', 'Iridaceae', 'flor', 2742454),
    ('Strelitzia reginae', 'Strelitziaceae', 'flor', 2763116),
    ('Heliconia rostrata', 'Heliconiaceae', 'flor', 2760967),
    ('Alcantarea imperialis', 'Bromeliaceae', 'flor', 2700429),
    ('Guzmania lingulata', 'Bromeliaceae', 'flor', 2699095),
    ('Tillandsia usneoides', 'Bromeliaceae', 'flor', 2695149),
    ('Camellia japonica', 'Theaceae', 'flor', 3189636),
    ('Lantana camara', 'Verbenaceae', 'flor', 2925303),
    ('Clusia fluminensis', 'Clusiaceae', 'flor', 5556496),
    ('Buxus sempervirens', 'Buxaceae', 'flor', 2984671),
    ('Portulaca grandiflora', 'Portulacaceae', 'flor', 3084700),
    ('Cyclamen persicum', 'Primulaceae', 'flor', 3169317),
    ('Calliandra tweedii', 'Fabaceae', 'flor', 2982053),
    ('Calliandra haematocephala', 'Fabaceae', 'flor', 2982155),
    ('Handroanthus chrysotrichus', 'Bignoniaceae', 'arvore', 4092405),
    ('Handroanthus impetiginosus', 'Bignoniaceae', 'arvore', 4092242),
    ('Pleroma mutabile', 'Melastomataceae', 'arvore', 5601379),
    ('Pleroma granulosum', 'Melastomataceae', 'arvore', 5601452),
    ('Licuala grandis', 'Arecaceae', 'arvore', 8008690),
    ('Pinus thunbergii', 'Pinaceae', 'arvore', 5285799),
    ('Zoysia japonica', 'Poaceae', 'grama', 2704737),
    ('Axonopus compressus', 'Poaceae', 'grama', 2705924),
    ('Ocimum basilicum', 'Lamiaceae', 'erva', 2927096),
    ('Mentha spicata', 'Lamiaceae', 'erva', 2927175),
    ('Salvia rosmarinus', 'Lamiaceae', 'erva', 10902460),
    ('Origanum vulgare', 'Lamiaceae', 'erva', 2926612),
    ('Origanum majorana', 'Lamiaceae', 'erva', 2926615),
    ('Thymus vulgaris', 'Lamiaceae', 'erva', 5341442),
    ('Salvia officinalis', 'Lamiaceae', 'erva', 2927004),
    ('Melissa officinalis', 'Lamiaceae', 'erva', 5341501),
    ('Coleus barbatus', 'Lamiaceae', 'erva', 8030165),
    ('Cymbopogon citratus', 'Poaceae', 'erva', 2705275),
    ('Cymbopogon winterianus', 'Poaceae', 'erva', 2705273),
    ('Petroselinum crispum', 'Apiaceae', 'erva', 7828157),
    ('Coriandrum sativum', 'Apiaceae', 'erva', 3034871),
    ('Anethum graveolens', 'Apiaceae', 'erva', 3034646),
    ('Foeniculum vulgare', 'Apiaceae', 'erva', 3034922),
    ('Allium fistulosum', 'Amaryllidaceae', 'erva', 2856504),
    ('Laurus nobilis', 'Lauraceae', 'erva', 3034015),
    ('Matricaria chamomilla', 'Asteraceae', 'erva', 8370958),
    ('Stevia rebaudiana', 'Asteraceae', 'erva', 3125557),
    ('Capsicum baccatum', 'Solanaceae', 'erva', 2932938),
    ('Capsicum frutescens', 'Solanaceae', 'erva', 8403992),
    ('Zingiber officinale', 'Zingiberaceae', 'erva', 2757280),
    ('Curcuma longa', 'Zingiberaceae', 'erva', 2757624),
    ('Pereskia aculeata', 'Cactaceae', 'erva', 5384215),
    ('Lactuca sativa', 'Asteraceae', 'hortalica', 7403263),
    ('Eruca vesicaria', 'Brassicaceae', 'hortalica', 5375920),
    ('Brassica oleracea var. acephala', 'Brassicaceae', 'hortalica', 10677932),
    ('Brassica oleracea var. italica', 'Brassicaceae', 'hortalica', 3042845),
    ('Brassica oleracea var. capitata', 'Brassicaceae', 'hortalica', 3042845),
    ('Brassica oleracea var. botrytis', 'Brassicaceae', 'hortalica', 3042845),
    ('Nasturtium officinale', 'Brassicaceae', 'hortalica', 7701037),
    ('Raphanus sativus', 'Brassicaceae', 'hortalica', 7678610),
    ('Brassica juncea', 'Brassicaceae', 'hortalica', 3042751),
    ('Spinacia oleracea', 'Amaranthaceae', 'hortalica', 3083647),
    ('Beta vulgaris', 'Amaranthaceae', 'hortalica', 8971274),
    ('Beta vulgaris var. cicla', 'Amaranthaceae', 'hortalica', 7539798),
    ('Solanum lycopersicum', 'Solanaceae', 'hortalica', 2930137),
    ('Solanum lycopersicum var. cerasiforme', 'Solanaceae', 'hortalica', 7904703),
    ('Capsicum annuum', 'Solanaceae', 'hortalica', 2932944),
    ('Solanum melongena', 'Solanaceae', 'hortalica', 2930617),
    ('Solanum aethiopicum', 'Solanaceae', 'hortalica', 2929847),
    ('Solanum tuberosum', 'Solanaceae', 'hortalica', 2930262),
    ('Cucumis sativus', 'Cucurbitaceae', 'hortalica', 2874569),
    ('Cucurbita pepo', 'Cucurbitaceae', 'hortalica', 2874508),
    ('Cucurbita moschata', 'Cucurbitaceae', 'hortalica', 7393329),
    ('Sechium edule', 'Cucurbitaceae', 'hortalica', 2874612),
    ('Citrullus lanatus', 'Cucurbitaceae', 'hortalica', 2874621),
    ('Abelmoschus esculentus', 'Malvaceae', 'hortalica', 3152707),
    ('Daucus carota', 'Apiaceae', 'hortalica', 3034742),
    ('Apium graveolens', 'Apiaceae', 'hortalica', 5371879),
    ('Allium cepa', 'Amaryllidaceae', 'hortalica', 2857697),
    ('Allium sativum', 'Amaryllidaceae', 'hortalica', 2856681),
    ('Allium ampeloprasum', 'Amaryllidaceae', 'hortalica', 2856037),
    ('Phaseolus vulgaris', 'Fabaceae', 'hortalica', 5350452),
    ('Lathyrus oleraceus', 'Fabaceae', 'hortalica', 5347846),
    ('Zea mays', 'Poaceae', 'hortalica', 5290052),
    ('Ipomoea batatas', 'Convolvulaceae', 'hortalica', 2928551),
    ('Manihot esculenta', 'Euphorbiaceae', 'hortalica', 3060998),
    ('Fragaria × ananassa', 'Rosaceae', 'hortalica', 3029912),
    ('Citrus × latifolia', 'Rutaceae', 'frutifera', 3831655),
    ('Citrus × limonia', 'Rutaceae', 'frutifera', NULL),
    ('Citrus × sinensis', 'Rutaceae', 'frutifera', NULL),
    ('Citrus reticulata', 'Rutaceae', 'frutifera', 3190172),
    ('Plinia cauliflora', 'Myrtaceae', 'frutifera', 5415571),
    ('Eugenia uniflora', 'Myrtaceae', 'frutifera', 5416458),
    ('Eugenia brasiliensis', 'Myrtaceae', 'frutifera', 5416882),
    ('Psidium guajava', 'Myrtaceae', 'frutifera', 5420380),
    ('Malpighia emarginata', 'Malpighiaceae', 'frutifera', 5421427),
    ('Morus nigra', 'Moraceae', 'frutifera', 5361888),
    ('Ficus carica', 'Moraceae', 'frutifera', 5361909),
    ('Mangifera indica', 'Anacardiaceae', 'frutifera', 3190638),
    ('Anacardium occidentale', 'Anacardiaceae', 'frutifera', 5421368),
    ('Musa spp.', 'Musaceae', 'frutifera', 2760990),
    ('Carica papaya', 'Caricaceae', 'frutifera', 2874484),
    ('Passiflora edulis', 'Passifloraceae', 'frutifera', 2874190),
    ('Persea americana', 'Lauraceae', 'frutifera', 3034046),
    ('Cocos nucifera', 'Arecaceae', 'frutifera', 2735117),
    ('Punica granatum', 'Lythraceae', 'frutifera', 5420901),
    ('Vaccinium corymbosum', 'Ericaceae', 'frutifera', 2882849),
    ('Ananas comosus', 'Bromeliaceae', 'frutifera', 5288819),
    ('Vitis vinifera', 'Vitaceae', 'frutifera', 5372392),
    ('Averrhoa carambola', 'Oxalidaceae', 'frutifera', 2891641),
    ('Selenicereus undatus', 'Cactaceae', 'frutifera', 10334868),
    ('Artocarpus heterophyllus', 'Moraceae', 'frutifera', 2984565)
    RETURNING id, scientific_name
)
INSERT INTO species_common_names (species_id, name, is_primary)
SELECT inserted.id, n.name, n.is_primary
FROM inserted
JOIN (
    VALUES
    ('Monstera deliciosa', 'costela-de-adão', true),
    ('Epipremnum aureum', 'jiboia', true),
    ('Philodendron hederaceum', 'filodendro-brasil', true),
    ('Philodendron hederaceum', 'filodendro-coração', false),
    ('Thaumatophyllum bipinnatifidum', 'guaimbê', true),
    ('Thaumatophyllum bipinnatifidum', 'filodendro-imbé', false),
    ('Zamioculcas zamiifolia', 'zamioculca', true),
    ('Spathiphyllum wallisii', 'lírio-da-paz', true),
    ('Anthurium andraeanum', 'antúrio', true),
    ('Dieffenbachia seguine', 'comigo-ninguém-pode', true),
    ('Aglaonema commutatum', 'aglaonema', true),
    ('Syngonium podophyllum', 'singônio', true),
    ('Caladium bicolor', 'tinhorão', true),
    ('Caladium bicolor', 'coração-de-jesus', false),
    ('Dracaena trifasciata', 'espada-de-são-jorge', true),
    ('Dracaena fragrans', 'dracena', true),
    ('Dracaena fragrans', 'pau-d''água', false),
    ('Dracaena marginata', 'dracena-de-madagascar', true),
    ('Dracaena sanderiana', 'bambu-da-sorte', true),
    ('Beaucarnea recurvata', 'pata-de-elefante', true),
    ('Chlorophytum comosum', 'clorofito', true),
    ('Chlorophytum comosum', 'gravatinha', false),
    ('Aspidistra elatior', 'aspidistra', true),
    ('Asparagus setaceus', 'aspargo-samambaia', true),
    ('Ficus lyrata', 'figueira-lira', true),
    ('Ficus elastica', 'falsa-seringueira', true),
    ('Ficus elastica', 'seringueira-de-jardim', false),
    ('Ficus elastica', 'figueira-da-borracha', false),
    ('Ficus elastica', 'árvore-da-borracha', false),
    ('Ficus benjamina', 'ficus-benjamina', true),
    ('Ficus benjamina', 'figueira-benjamim', false),
    ('Maranta leuconeura', 'maranta', true),
    ('Goeppertia makoyana', 'calateia', true),
    ('Nephrolepis exaltata', 'samambaia-americana', true),
    ('Nephrolepis exaltata', 'samambaia', false),
    ('Adiantum raddianum', 'avenca', true),
    ('Platycerium bifurcatum', 'chifre-de-veado', true),
    ('Rhapis excelsa', 'palmeira-ráfis', true),
    ('Dypsis lutescens', 'areca-bambu', true),
    ('Chamaedorea elegans', 'camedórea-elegante', true),
    ('Chamaedorea elegans', 'palmeira-de-salão', false),
    ('Peperomia obtusifolia', 'peperômia', true),
    ('Pilea peperomioides', 'pilea', true),
    ('Pilea peperomioides', 'planta-dinheiro-chinesa', false),
    ('Begonia maculata', 'begônia-maculata', true),
    ('Tradescantia zebrina', 'lambari', true),
    ('Tradescantia zebrina', 'tradescância-zebrina', false),
    ('Tradescantia pallida', 'coração-roxo', true),
    ('Hedera helix', 'hera', true),
    ('Heptapleurum arboricola', 'cheflera', true),
    ('Codiaeum variegatum', 'cróton', true),
    ('Aloe vera', 'babosa', true),
    ('Aloe vera', 'aloe', false),
    ('Haworthiopsis attenuata', 'haworthia-zebra', true),
    ('Crassula ovata', 'planta-jade', true),
    ('Crassula ovata', 'árvore-de-jade', false),
    ('Echeveria elegans', 'echevéria', true),
    ('Echeveria elegans', 'rosa-de-pedra', false),
    ('Kalanchoe blossfeldiana', 'calanchoê', true),
    ('Kalanchoe blossfeldiana', 'flor-da-fortuna', false),
    ('Sedum morganianum', 'rabo-de-burro', true),
    ('Graptopetalum paraguayense', 'planta-fantasma', true),
    ('Curio rowleyanus', 'colar-de-pérolas', true),
    ('Euphorbia milii', 'coroa-de-cristo', true),
    ('Schlumbergera truncata', 'flor-de-maio', true),
    ('Opuntia microdasys', 'cacto-orelha-de-coelho', true),
    ('Cereus jamacaru', 'mandacaru', true),
    ('Adenium obesum', 'rosa-do-deserto', true),
    ('Agave americana', 'agave', true),
    ('Cleistocactus winteri subsp. colademono', 'cacto-rabo-de-macaco', true),
    ('Cleistocactus winteri subsp. colademono', 'rabo-de-macaco', false),
    ('Aporocactus flagelliformis', 'rabo-de-rato', true),
    ('Aporocactus flagelliformis', 'rabo-de-macaco', false),
    ('Rosa × hybrida', 'roseira', true),
    ('Rosa × hybrida', 'rosa', false),
    ('Phalaenopsis spp.', 'orquídea-borboleta', true),
    ('Phalaenopsis spp.', 'falenópsis', false),
    ('Dendrobium nobile', 'orquídea-olho-de-boneca', true),
    ('Dendrobium nobile', 'dendróbio', false),
    ('Cattleya labiata', 'catleia', true),
    ('Oncidium spp.', 'orquídea-chuva-de-ouro', true),
    ('Oncidium spp.', 'oncídio', false),
    ('Streptocarpus ionanthus', 'violeta-africana', true),
    ('Hydrangea macrophylla', 'hortênsia', true),
    ('Rhododendron simsii', 'azaleia', true),
    ('Bougainvillea spectabilis', 'primavera', true),
    ('Bougainvillea spectabilis', 'buganvília', false),
    ('Hibiscus rosa-sinensis', 'hibisco', true),
    ('Ixora coccinea', 'ixora', true),
    ('Gardenia jasminoides', 'gardênia', true),
    ('Trachelospermum jasminoides', 'jasmim-estrela', true),
    ('Allamanda cathartica', 'alamanda', true),
    ('Cestrum nocturnum', 'dama-da-noite', true),
    ('Brunfelsia uniflora', 'manacá-de-cheiro', true),
    ('Petunia × atkinsiana', 'petúnia', true),
    ('Lavandula angustifolia', 'lavanda', true),
    ('Pelargonium × hortorum', 'gerânio', true),
    ('Impatiens walleriana', 'maria-sem-vergonha', true),
    ('Impatiens hawkeri', 'beijo-pintado', true),
    ('Viola × wittrockiana', 'amor-perfeito', true),
    ('Helianthus annuus', 'girassol', true),
    ('Leucanthemum vulgare', 'margarida', true),
    ('Chrysanthemum × morifolium', 'crisântemo', true),
    ('Gerbera jamesonii', 'gérbera', true),
    ('Tagetes erecta', 'cravo-de-defunto', true),
    ('Zinnia elegans', 'zínia', true),
    ('Dianthus caryophyllus', 'cravo', true),
    ('Lilium spp.', 'lírio', true),
    ('Agapanthus africanus', 'agapanto', true),
    ('Hippeastrum spp.', 'amarílis', true),
    ('Dietes bicolor', 'moreia', true),
    ('Strelitzia reginae', 'ave-do-paraíso', true),
    ('Heliconia rostrata', 'helicônia', true),
    ('Alcantarea imperialis', 'bromélia-imperial', true),
    ('Guzmania lingulata', 'bromélia-guzmânia', true),
    ('Tillandsia usneoides', 'barba-de-velho', true),
    ('Camellia japonica', 'camélia', true),
    ('Lantana camara', 'lantana', true),
    ('Lantana camara', 'cambará', false),
    ('Clusia fluminensis', 'clúsia', true),
    ('Buxus sempervirens', 'buxinho', true),
    ('Portulaca grandiflora', 'onze-horas', true),
    ('Cyclamen persicum', 'ciclame', true),
    ('Calliandra tweedii', 'caliandra-vermelha', true),
    ('Calliandra tweedii', 'caliandra', false),
    ('Calliandra tweedii', 'esponjinha-vermelha', false),
    ('Calliandra tweedii', 'esponjinha-sangue', false),
    ('Calliandra haematocephala', 'caliandra-vermelha', true),
    ('Calliandra haematocephala', 'esponjinha-de-sangue', false),
    ('Calliandra haematocephala', 'esponjinha', false),
    ('Handroanthus chrysotrichus', 'ipê-amarelo', true),
    ('Handroanthus impetiginosus', 'ipê-roxo', true),
    ('Pleroma mutabile', 'manacá-da-serra', true),
    ('Pleroma granulosum', 'quaresmeira', true),
    ('Licuala grandis', 'palmeira-leque', true),
    ('Pinus thunbergii', 'pinheiro-negro-japonês', true),
    ('Pinus thunbergii', 'pinheiro-negro', false),
    ('Zoysia japonica', 'grama-esmeralda', true),
    ('Axonopus compressus', 'grama-são-carlos', true),
    ('Ocimum basilicum', 'manjericão', true),
    ('Mentha spicata', 'hortelã', true),
    ('Salvia rosmarinus', 'alecrim', true),
    ('Origanum vulgare', 'orégano', true),
    ('Origanum majorana', 'manjerona', true),
    ('Thymus vulgaris', 'tomilho', true),
    ('Salvia officinalis', 'sálvia', true),
    ('Melissa officinalis', 'melissa', true),
    ('Melissa officinalis', 'erva-cidreira', false),
    ('Coleus barbatus', 'boldo', true),
    ('Cymbopogon citratus', 'capim-limão', true),
    ('Cymbopogon citratus', 'capim-santo', false),
    ('Cymbopogon winterianus', 'citronela', true),
    ('Petroselinum crispum', 'salsinha', true),
    ('Petroselinum crispum', 'salsa', false),
    ('Coriandrum sativum', 'coentro', true),
    ('Anethum graveolens', 'endro', true),
    ('Foeniculum vulgare', 'erva-doce', true),
    ('Foeniculum vulgare', 'funcho', false),
    ('Allium fistulosum', 'cebolinha', true),
    ('Laurus nobilis', 'louro', true),
    ('Matricaria chamomilla', 'camomila', true),
    ('Stevia rebaudiana', 'estévia', true),
    ('Capsicum baccatum', 'pimenta-dedo-de-moça', true),
    ('Capsicum frutescens', 'pimenta-malagueta', true),
    ('Zingiber officinale', 'gengibre', true),
    ('Curcuma longa', 'açafrão-da-terra', true),
    ('Curcuma longa', 'cúrcuma', false),
    ('Pereskia aculeata', 'ora-pro-nóbis', true),
    ('Lactuca sativa', 'alface', true),
    ('Eruca vesicaria', 'rúcula', true),
    ('Brassica oleracea var. acephala', 'couve', true),
    ('Brassica oleracea var. italica', 'brócolis', true),
    ('Brassica oleracea var. capitata', 'repolho', true),
    ('Brassica oleracea var. botrytis', 'couve-flor', true),
    ('Nasturtium officinale', 'agrião', true),
    ('Raphanus sativus', 'rabanete', true),
    ('Brassica juncea', 'mostarda', true),
    ('Spinacia oleracea', 'espinafre', true),
    ('Beta vulgaris', 'beterraba', true),
    ('Beta vulgaris var. cicla', 'acelga', true),
    ('Solanum lycopersicum', 'tomate', true),
    ('Solanum lycopersicum var. cerasiforme', 'tomate-cereja', true),
    ('Capsicum annuum', 'pimentão', true),
    ('Solanum melongena', 'berinjela', true),
    ('Solanum aethiopicum', 'jiló', true),
    ('Solanum tuberosum', 'batata', true),
    ('Cucumis sativus', 'pepino', true),
    ('Cucurbita pepo', 'abobrinha', true),
    ('Cucurbita moschata', 'abóbora', true),
    ('Sechium edule', 'chuchu', true),
    ('Citrullus lanatus', 'melancia', true),
    ('Abelmoschus esculentus', 'quiabo', true),
    ('Daucus carota', 'cenoura', true),
    ('Apium graveolens', 'salsão', true),
    ('Apium graveolens', 'aipo', false),
    ('Allium cepa', 'cebola', true),
    ('Allium sativum', 'alho', true),
    ('Allium ampeloprasum', 'alho-poró', true),
    ('Phaseolus vulgaris', 'feijão-vagem', true),
    ('Phaseolus vulgaris', 'feijão', false),
    ('Lathyrus oleraceus', 'ervilha', true),
    ('Zea mays', 'milho', true),
    ('Ipomoea batatas', 'batata-doce', true),
    ('Manihot esculenta', 'mandioca', true),
    ('Manihot esculenta', 'aipim', false),
    ('Manihot esculenta', 'macaxeira', false),
    ('Fragaria × ananassa', 'morango', true),
    ('Citrus × latifolia', 'limoeiro-taiti', true),
    ('Citrus × latifolia', 'limão-taiti', false),
    ('Citrus × limonia', 'limão-cravo', true),
    ('Citrus × sinensis', 'laranjeira', true),
    ('Citrus × sinensis', 'laranja', false),
    ('Citrus reticulata', 'tangerineira', true),
    ('Citrus reticulata', 'mexeriqueira', false),
    ('Citrus reticulata', 'tangerina', false),
    ('Plinia cauliflora', 'jabuticabeira', true),
    ('Plinia cauliflora', 'jabuticaba', false),
    ('Eugenia uniflora', 'pitangueira', true),
    ('Eugenia uniflora', 'pitanga', false),
    ('Eugenia brasiliensis', 'grumixameira', true),
    ('Eugenia brasiliensis', 'grumixama', false),
    ('Psidium guajava', 'goiabeira', true),
    ('Psidium guajava', 'goiaba', false),
    ('Malpighia emarginata', 'aceroleira', true),
    ('Malpighia emarginata', 'acerola', false),
    ('Morus nigra', 'amoreira', true),
    ('Morus nigra', 'amora', false),
    ('Ficus carica', 'figueira', true),
    ('Ficus carica', 'figo', false),
    ('Mangifera indica', 'mangueira', true),
    ('Mangifera indica', 'manga', false),
    ('Anacardium occidentale', 'cajueiro', true),
    ('Anacardium occidentale', 'caju', false),
    ('Musa spp.', 'bananeira', true),
    ('Musa spp.', 'banana', false),
    ('Carica papaya', 'mamoeiro', true),
    ('Carica papaya', 'mamão', false),
    ('Passiflora edulis', 'maracujazeiro', true),
    ('Passiflora edulis', 'maracujá', false),
    ('Persea americana', 'abacateiro', true),
    ('Persea americana', 'abacate', false),
    ('Cocos nucifera', 'coqueiro', true),
    ('Cocos nucifera', 'coco', false),
    ('Punica granatum', 'romãzeira', true),
    ('Punica granatum', 'romã', false),
    ('Vaccinium corymbosum', 'mirtilo', true),
    ('Ananas comosus', 'abacaxizeiro', true),
    ('Ananas comosus', 'abacaxi', false),
    ('Vitis vinifera', 'videira', true),
    ('Vitis vinifera', 'uva', false),
    ('Averrhoa carambola', 'caramboleira', true),
    ('Averrhoa carambola', 'carambola', false),
    ('Selenicereus undatus', 'pitaia', true),
    ('Artocarpus heterophyllus', 'jaqueira', true),
    ('Artocarpus heterophyllus', 'jaca', false)
) AS n (scientific_name, name, is_primary) USING (scientific_name);
